name: Build with Quality Check
on:
  push:
    branches:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/build-with-shellcheck.yml
  test-ubuntu:
    needs: build
    uses: ./.github/workflows/test-with-ubuntu.yml
  test-debian:
    needs: build
    uses: ./.github/workflows/test-with-debian.yml
