name: Deployment
on:
  release:
    types: [created]

jobs:
  quality:
    uses: ./.github/workflows/quality-shellcheck.yml
  build:
    needs: quality
    uses: ./.github/workflows/build-deb-file.yml
  test-ubuntu:
    needs: build
    uses: ./.github/workflows/test-with-ubuntu.yml
  test-debian:
    needs: build
    uses: ./.github/workflows/test-with-debian.yml
  release-assets:
    needs: [test-ubuntu, test-debian]
    uses: ./.github/workflows/deploy-github-release-assets.yml
    secrets:
      TOKEN_TO_UPLOAD_ASSETS: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
  siakhooi-apt:
    needs: [test-ubuntu, test-debian]
    uses: ./.github/workflows/publish-to-siakhooi-apt.yml
    secrets:
      PUBLISH_TO_APT_GITHUB_TOKEN: ${{ secrets.PUBLISH_TO_APT_GITHUB_TOKEN }}
